spring.application.name=mybatis
server.port=${PORT:8080}

# .env
spring.config.import=optional:file:.env[.properties]

# 프로파일
spring.profiles.active=dev
# application 설정 파일을 dev, prod 등으로 세분화해서 관리 가능
# 현 상황에서는 기본을 dev로 가져가겠다 -> 여러 방식으로 바꿀 수 있음

# 뷰 리졸버
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 마이바티스 설정 (데이터소스 제외)
mybatis.mapper-locations=classpath:mapper/**/*.xml
# mappers라는 폴더 아래에 있는 xml 포맷이라면 세부 경로 상관없이 사용
mybatis.type-aliases-package=com.example.mybatis.entity
# 어디에 데이터베이스에서 사용해줄 엔터티 등이 존재하는가?
mybatis.configuration.map-underscore-to-camel-case=true
# hello_world -> helloWorld (스네이크케
# 이스를 카멜케이스로 바꿔주는 기능)